/**
 * MediaAsset Model - Store uploaded images and videos
 */

const mongoose = require('mongoose');

const mediaAssetSchema = new mongoose.Schema(
  {
    // File info
    filename: {
      type: String,
      required: true,
    },
    mime: {
      type: String,
      required: true,
      enum: [
        'image/jpeg',
        'image/png',
        'image/gif',
        'image/webp',
        'image/svg+xml',
        'video/mp4',
        'video/webm',
        'video/ogg',
      ],
    },
    size: {
      type: Number,
      required: true,
    },

    // Type
    type: {
      type: String,
      required: true,
      enum: ['image', 'video'],
    },

    // Storage
    storageKeyOrPath: {
      type: String,
      required: true,
      // e.g., "uploads/media-1704067200000-abc123.jpg"
    },

    // URLs (generated by server)
    url: {
      type: String,
      required: true,
      // e.g., "/api/media/serve/507f1f77bcf86cd799439011"
    },
    thumbnailUrl: {
      type: String,
      // e.g., "/api/media/serve/507f1f77bcf86cd799439011?thumbnail=true"
    },

    // Image metadata
    width: {
      type: Number,
      // Only for images
    },
    height: {
      type: Number,
      // Only for images
    },

    // Video metadata
    duration: {
      type: Number,
      // Only for videos, in seconds
    },

    // Ownership
    uploadedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      // Optional: track who uploaded
    },

    // Soft delete
    deletedAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

// Indexes
mediaAssetSchema.index({ createdAt: -1 });
mediaAssetSchema.index({ type: 1 });
mediaAssetSchema.index({ filename: 1 });
mediaAssetSchema.index({ uploadedBy: 1 });

// Query helper to exclude soft-deleted
mediaAssetSchema.query.active = function () {
  return this.where({ deletedAt: null });
};

module.exports = mongoose.model('MediaAsset', mediaAssetSchema);

